package uk.co.steffandroid.advent

fun main(args: Array<String>) {
    println("Day 1 - Part 1: " + Day01().part1())
    println("Day 1 - Part 2: " + Day01().part2())
    println("Day 2 - Part 1: " + Day02().part1())
    println("Day 2 - Part 2: " + Day02().part2())
    println("Day 3 - Part 1: " + Day03().part1())
    println("Day 3 - Part 2: " + Day03().part2())
    println("Day 4 - Part 1: " + Day04().part1())
    println("Day 4 - Part 2: " + Day04().part2())
    println("Day 5 - Part 1: " + Day05().part1())
    println("Day 5 - Part 2: " + Day05().part2())
    println("Day 6 - Part 1: " + Day06().part1())
    println("Day 6 - Part 2: " + Day06().part2())
    println("Day 7 - Part 1: " + Day07().part1())
    println("Day 7 - Part 2: " + Day07().part2())
    println("Day 8 - Part 1: " + Day08().part1())
    println("Day 8 - Part 2: " + Day08().part2())
//    println("Day 9 - Part 1: " + Day09().part1())
//    println("Day 9 - Part 2: " + Day09().part2())
    println("Day 10 - Part 1: " + Day10().part1())
    println("Day 10 - Part 2: " + Day10().part2())
//    println("Day 11 - Part 1: " + Day11().part1())
//    println("Day 11 - Part 2: " + Day11().part2())
    println("Day 12 - Part 1: " + Day12().part1())
    println("Day 12 - Part 2: " + Day12().part2())
//    println("Day 13 - Part 1: " + Day13().part1())
//    println("Day 13 - Part 2: " + Day13().part2())
}
